apiVersion: batch/v1
kind: Job
metadata:
  name: posthookjob-demo
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: demo
        image: alpine
        args:
        - /bin/sh
        - -c
        - echo "Command executed from Posthook Job"
      restartPolicy: OnFailure