apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.200
    path: "/var/nfs/data0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.200
    path: "/var/nfs/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.200
    path: "/var/nfs/data2"